# Generated by Django 3.2.9 on 2021-11-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbCategoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbProcesso',
            fields=[
                ('processo_id', models.AutoField(primary_key=True, serialize=False)),
                ('processo_titulo', models.CharField(max_length=200)),
                ('processo_descricao', models.CharField(max_length=200)),
                ('processo_date', models.DateField(verbose_name='data de publicacao')),
                ('processo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tbcategoria')),
            ],
        ),
    ]
